### ISSUE TITLE
sensitivity to light

### ISSUE THREAD

**Issue by Roms1383** [cyb3rpsych0s1s/4ddicted#28]
a cool side effect for being severely addicted to Memory Booster could be light sensitivity.

from a quick Google search:

> A migraine is a headache that can cause severe throbbing pain or a pulsing sensation, usually on one side of the head. It's often accompanied by nausea, vomiting, and **extreme sensitivity to light and sound**.
```[tasklist]
### Tasks
- [ ] search status effect associated with flash grenade
- [ ] reuse or create a stat modifier to extend status effect
- [ ] add additional potential inducers for status effect ?
```
